version: "3.8"
services:
  mysqldb:
    image: mysql:latest

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USE=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=studentregistration
    ports:
    - 3307:3306

  app:
    image: coursereg
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure

    ports:
      - 8585:8585
    networks:
      - mysqldb

    stdin_open: true
    tty: true
networks:
  mysqldb:
    external: true

